### PR TITLE
fix #12: final thankyou page

### LINKED ISSUE #12: Add some CTA buttons and measure their clicks
Job Story: When the user leaves the study (by choice? by default?), show them actions to take and measure the clicks, so we can learn which actions indicate retention and/or growth.

Some example actions:

* "Make Firefox my default browser"
* "Share Firefox" (Twitter/Facebook link?)

### PR DESCRIPTION
**Pull request by groovecoder**
Needs some word-smithing and UX review by @jsavory.

@gregglind - I'm `tabs.open`ing this thank-you page during study `cleanup`. Will the user **also** see the post-study survey url? I.e., so they'll see **both** tabs open when the study ends?

image

### CODE REVIEW

**Comment by groovecoder** [comment]
@casebenton - can you check this out ... and tell me if/how to fix the Travis error on it? 😉

**Comment by gregglind** [comment]
Claim (naive):  they will see both.  I also think this is OK, because they opted in, and really, it's not that much annoyance.
You can control this, several ways.

**Comment by bentoncase** [comment]
@groovecoder I just turned travis off for now, as I don't think it's related (I'm still working on getting it operational)

**Comment by bentoncase** [comment]
@groovecoder update: the travis error is definitely unrelated (it's an issue with es8 and a grunt parser) so please ignore for now :)

**Comment by jsavory** [comment]
Looking good so far, I think the biggest issue is the button right now, it doesn't look very clickable. I would try reducing the size similar to what I have in the spec, darkening the border a bit (the colour I found was C3C2C2) and making the font size slightly smaller (try size 13 if the regular text is size 14). 

Also the facebook icon looks off center, I am thinking because the background colour is the same as the background of the icon all you can see if the 'f'. Is there any way we can just use the 'f' rather than the full icon?

**Comment by groovecoder** [comment]
Updated:

image

**Pull request merged**
